import streamlit as st
import pandas as pd
import sqlite3
import os
import plotly.express as px
from data_validation import run_continuous_audit

# Set page configuration
st.set_page_config(page_title="Credit Risk Analytics Dashboard", layout="wide")

# 1. Database Connection & Data Ingestion
@st.cache_data
def load_data_from_db():
    db_path = os.path.join('database', 'credit_risk.db')
    if not os.path.exists(db_path):
        st.error("Database not found! Please run 'python src/initialize_db.py' first.")
        return pd.DataFrame()
    
    conn = sqlite3.connect(db_path)
    # Reading data back into memory for the frontend application
    df = pd.read_sql_query("SELECT * FROM loans", conn)
    conn.close()
    return df

raw_data = load_data_from_db()

if not raw_data.empty:
    # 2. Continuous Auditing Implementation
    # Pass data through our data validation engine before displaying it
    cleaned_data, audit_results = run_continuous_audit(raw_data)

    # 3. Sidebar Application Layout
    st.sidebar.title("Dashboard Controls")
    st.sidebar.markdown("---")
    
    # Filters
    selected_grade = st.sidebar.multiselect(
        "Select Risk Grade:", 
        options=sorted(cleaned_data['grade'].dropna().unique()),
        default=sorted(cleaned_data['grade'].dropna().unique())
    )
    
    # Filter dataset based on selection
    filtered_df = cleaned_data[cleaned_data['grade'].isin(selected_grade)]

    # 4. Main UI Layout
    st.title("📊 Credit Risk Analytics Dashboard")
    st.caption("Data Engineering & Continuous Auditing Interface")
    
    # Metric KPI Row
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Total Loans Monitored", f"{len(filtered_df):,}")
    with col2:
        st.metric("Total Portfolio Value", f"${filtered_df['loan_amnt'].sum():,.2f}")
    with col3:
        avg_rate = filtered_df['int_rate'].mean()
        st.metric("Avg Interest Rate", f"{avg_rate:.2f}%" if not pd.isna(avg_rate) else "0.00%")
    with col4:
        # Simple risk heuristic: Charge Off/Default count as default rate
        total_loans = len(filtered_df)
        default_loans = len(filtered_df[filtered_df['loan_status'].isin(['Charged Off', 'Default'])])
        def_rate = (default_loans / total_loans * 100) if total_loans > 0 else 0
        st.metric("Portfolio Default Rate", f"{def_rate:.2f}%")

    st.markdown("---")

    # Tabs for Data Visualization vs. Auditing Logs
    tab1, tab2 = st.tabs(["📉 Portfolio Analytics", "🔍 Continuous Auditing System"])

    with tab1:
        st.subheader("Risk Distribution & Metrics")
        
        v_col1, v_col2 = st.columns(2)
        with v_col1:
            # Distribution of Loan Amounts
            fig_hist = px.histogram(filtered_df, x="loan_amnt", nbins=30, 
                                    title="Loan Amount Distribution",
                                    labels={'loan_amnt': 'Loan Amount ($)'},
                                    color_discrete_sequence=['#1f77b4'])
            st.plotly_chart(fig_hist, use_container_width=True)
            
        with v_col2:
            # Loan Status Breakdown
            status_counts = filtered_df['loan_status'].value_counts().reset_index()
            status_counts.columns = ['loan_status', 'count']
            fig_pie = px.pie(status_counts, values='count', names='loan_status', 
                             title="Loan Portfolio Status Summary",
                             hole=0.4)
            st.plotly_chart(fig_pie, use_container_width=True)

    with tab2:
        st.subheader("Real-Time Automated Data Quality Logs")
        
        # Display validation results directly on the dashboard
        if audit_results["success"]:
            st.success("Core Database Integrity Checks: PASSED")
        else:
            st.warning("Core Database Integrity Checks: ANOMALIES DETECTED & SOLVED")
            
        # Output the structural logs generated by the script
        for log in audit_results["logs"]:
            st.code(log, language="text")
            
        # Show a summary grid of caught metrics
        s_col1, s_col2 = st.columns(2)
        s_col1.metric("Duplicate Primary Keys Found", audit_results["duplicate_count"], delta_color="inverse")
        s_col2.metric("Sequence/Format Discrepancies", audit_results["sequence_errors"], delta_color="inverse")
        